version: '3'
services:
  php:
    build:
      context: ./docker/php
    networks:
      - livres-net
    container_name: livres-php
    volumes:
      - .:/srv/app
  https:
    build:
      context: ./docker/nginx
    networks:
      - livres-net
    hostname: livresapp
    ports:
      - 8443:443
    volumes:
      - .:/srv/app
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/default.conf
    container_name: livres-nginx

networks:
  livres-net:
    driver: bridge